test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  project: u-tube
  credentials: <%= Rails.application.credentials.gcskey.to_json %>
  bucket: u-tube